# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Cat',
        ),
    ]
